-- Enum values mirror packages/shared/src/types/domain.ts exactly. Keep the
-- two in sync by hand - Postgres enums and TypeScript union types don't share
-- a single source of truth, so any change here needs a matching change there
-- (and a new migration; Postgres enums can only be extended, not edited, once
-- created without ALTER TYPE ... ADD VALUE).

CREATE TYPE platform_type AS ENUM ('ANDROID', 'IPHONE', 'OTHER');
CREATE TYPE sim_type AS ENUM ('PHYSICAL', 'ESIM', 'DUAL', 'UNKNOWN');
CREATE TYPE incident_type AS ENUM ('LOST', 'STOLEN', 'UNSURE');

CREATE TYPE case_status AS ENUM (
  'NEW',
  'ASSESSING',
  'LOCATING',
  'DEVICE_FOUND',
  'DEVICE_OFFLINE',
  'SECURING',
  'SIM_PROTECTION',
  'ACCOUNT_RECOVERY',
  'FINANCIAL_PROTECTION',
  'POLICE_REPORT',
  'CEIR_PENDING',
  'CEIR_SUBMITTED',
  'MONITORING',
  'RECOVERED',
  'ERASED',
  'CLOSED'
);

CREATE TYPE risk_level AS ENUM ('CRITICAL', 'HIGH', 'MEDIUM', 'LOW');
CREATE TYPE tri_state_answer AS ENUM ('YES', 'NO', 'UNSURE');

CREATE TYPE sim_access_status AS ENUM (
  'ANOTHER_DEVICE_HAS_ACCESS',
  'LOST_WITH_PHONE',
  'SIM_ALREADY_BLOCKED',
  'UNSURE'
);

CREATE TYPE sensitive_app_type AS ENUM (
  'BANKING',
  'UPI',
  'EMAIL',
  'SOCIAL_MEDIA',
  'PASSWORD_MANAGER',
  'AUTHENTICATOR',
  'WORK_ACCOUNTS'
);

CREATE TYPE recovery_action_type AS ENUM (
  'LOCATE_DEVICE',
  'RING_DEVICE',
  'NEARBY_SEARCH',
  'SECURE_DEVICE',
  'SIM_PROTECTION',
  'ACCOUNT_RECOVERY',
  'FINANCIAL_PROTECTION',
  'POLICE_REPORT',
  'CEIR_SUBMISSION',
  'EVIDENCE_COLLECTION',
  'MONITOR'
);

CREATE TYPE recovery_action_status AS ENUM ('PENDING', 'BLOCKED', 'IN_PROGRESS', 'COMPLETED', 'SKIPPED');

CREATE TYPE location_source AS ENUM (
  'AUTHORIZED_INTEGRATION',
  'USER_CONFIRMED',
  'USER_ENTERED',
  'OTHER_VERIFIED_SOURCE'
);

CREATE TYPE verification_status AS ENUM (
  'SYSTEM_VERIFIED',
  'USER_REPORTED',
  'AI_GENERATED',
  'EXTERNAL_VERIFIED',
  'UNVERIFIED'
);

CREATE TYPE evidence_category AS ENUM (
  'PURCHASE_INVOICE',
  'DEVICE_PHOTO',
  'IMEI_SERIAL_DOCUMENT',
  'LOCATION_SCREENSHOT',
  'POLICE_COMPLAINT',
  'POLICE_ACKNOWLEDGEMENT',
  'CEIR_ACKNOWLEDGEMENT',
  'CARRIER_SIM_DOCUMENT',
  'OTHER'
);

CREATE TYPE malware_scan_status AS ENUM ('PENDING', 'CLEAN', 'FLAGGED', 'SKIPPED');

CREATE TYPE timeline_event_type AS ENUM (
  'CASE_CREATED',
  'RISK_ASSESSED',
  'LOCATION_OBSERVATION_RECORDED',
  'DEVICE_FINDING_OPENED',
  'DEVICE_SECURED',
  'SIM_PROTECTION_STARTED',
  'SIM_PROTECTION_COMPLETED',
  'ACCOUNT_RECOVERY_STARTED',
  'ACCOUNT_RECOVERY_COMPLETED',
  'FINANCIAL_PROTECTION_COMPLETED',
  'POLICE_COMPLAINT_CREATED',
  'POLICE_COMPLAINT_APPROVED',
  'CEIR_SUBMITTED',
  'CEIR_STATUS_UPDATED',
  'EVIDENCE_UPLOADED',
  'DEVICE_RECOVERED',
  'DEVICE_ERASED',
  'CASE_CLOSED',
  'USER_NOTE'
);

CREATE TYPE timeline_event_source AS ENUM ('SYSTEM', 'USER', 'AI_AGENT', 'EXTERNAL_INTEGRATION');

CREATE TYPE police_report_status AS ENUM ('DRAFT', 'APPROVED', 'USER_MARKED_SUBMITTED');

CREATE TYPE ceir_status AS ENUM (
  'NOT_READY',
  'READY',
  'SUBMITTED',
  'PROCESSING',
  'BLOCKED',
  'UNBLOCK_REQUESTED',
  'UNBLOCKED',
  'UNKNOWN'
);

CREATE TYPE ceir_checklist_item AS ENUM (
  'IMEI_INFORMATION',
  'MOBILE_NUMBER',
  'DEVICE_DETAILS',
  'POLICE_REPORT',
  'IDENTITY_DOCUMENT',
  'PURCHASE_INVOICE',
  'REPLACEMENT_SIM_STATUS',
  'OTHER'
);

CREATE TYPE notification_type AS ENUM (
  'CRITICAL_ACTION_PENDING',
  'ACCOUNT_RECOVERY_UPDATE',
  'SIM_STATUS_UPDATE',
  'CEIR_FOLLOWUP_REMINDER',
  'CASE_INACTIVITY',
  'EVIDENCE_REMINDER',
  'DEVICE_RECOVERY_CHECKLIST'
);
